### ISSUE TITLE
Reset Skill Tree

### ISSUE THREAD

**Issue by andrico1234** [andrico1234/beautiful-skill-tree#1]
This might be a good challenging item for someone with little React knowledge to work on.

We want a button that sets everything to 0. It will require familiarity with the context api, so do let me know if you want to pick this up and we can run through things.

Replacing the individual context provider with a single one could work. I initially went against this as it came at a performance cost, but this might have some clues as to how we can have a single provider and no unnecessary rerenders

https://frontarm.com/james-k-nelson/react-context-performance/

**Comment by juanmanual** [comment]
Implementing #16 would make this implementation trivial. Just set the top level node of the skill tree to not 'selected'.

**Comment by andrico1234** [comment]
I would welcome the implementation you referenced, but I'd also like ways for developers to programmatically reset the skill tree, even through exposing the method via the SkillTreeGroup component. No reason we can't have both
