### ISSUE TITLE
Cascade deselection of prerequisite nodes

### ISSUE THREAD

**Issue by juanmanual** [andrico1234/beautiful-skill-tree#16]
Whenever a prerequisite node is de-selected (current state set to anything other than 'selected' - usually 'unlocked'), its children still remain selected. This can be confusing because that node can then be unselected but cannot be selected again unless its prerequisite nodes are selected again. 

If accepted, this issue would implement cascading behavior to the deselection of nodes. That is, it would be invalid for a node to be selected and its prerequisite node(s) not to be selected.

- [x] Add tests to verify cascading deselection is enforced
- [x] Change behavior in SkillNode to update the current state to not be 'selected' (and to be 'locked') if the current state of its parent is updated to no longer be 'selected'

**Comment by andrico1234** [comment]
I agree that this is a usability issue. I'd like to see your thoughts on implementation. Right now each node has only knowledge of its direct parent's Id and state, and nothing else, but each Node has knowledge of all its child nodes. I've got a few ideas on how to implement this, but I'd like to hear some of your ideas

**Comment by juanmanual** [comment]
Since the child already responds to change of state from its parent, I have
an implementation that sets a node’s state to locked if none of its parents
are selected. Then, since that node’s state has been updated and is not
selected, it’s children are locked too. I  was waiting to submit it until I
can write tests for the behavior, but I can submit it as a work in progress.

**Comment by andrico1234** [comment]
That sounds great, I'd love to see a WIP PR. As part of the issue, can you reference some performance testing you've performed, even from within the browser console.
