### ISSUE TITLE
Semantic error TS7016: Could not find a declaration file  for module

### ISSUE THREAD

**Issue by huesoamz** [andrico1234/beautiful-skill-tree#41]
(typescript) Error: C:/xampp/htdocs/dev/beautiful-skill-tree-master/src/componen
ts/SkillNode.tsx(9,32): semantic error TS7016: Could not find a declaration file
 for module '../../'. 'C:/xampp/htdocs/dev/beautiful-skill-tree-master/dist/inde
x.js' implicitly has an 'any' type.

fix:  on tsconfig.json

    "noImplicitAny": false,

**Comment by andrico1234** [comment]
Hey, thanks for filing an issue. 

Can you provide some more details about when you're seeing this issue, maybe a code snippet?
Does this issue come in the compiler when running your application or the package locally?

When I'm in the `SkillNode.tsx` file I don't have any issue with the typings file not being found, the intellisense on line 9 directs me to the corresponding file.

I also tried deleting and rebuilding the dist package incase a recent build may have prevent the typings file from being built but it doesn't seem to be the case.

I would rather not make my TypeScript set up more lenient for something I can't replicate.

**Comment by andrico1234** [comment]
I'm actually getting the issue when I clone the repo and try building it. 

I'll take a look at why this is the case

**Comment by andrico1234** [comment]
I found the issue and am fixing it now, will release it as part of v1.0.1.

In my `SkillNode.tsx` file
```
import { SkillThemeType } from '../../';
```
Should have been:
```
import { SkillThemeType } from '../';
```
For some reason, my local environment was able to resolve the types file, even though the component should have been trying to access the `index.tsx` file in the `src` directory. Very weird, and i'm so happy that you took the time to file an issue for this!

**Comment by andrico1234** [comment]
Please confirm that `v1.0.1` works for you and I can close this issue :)

**Comment by huesoamz** [comment]
Hi!, thanks for answer too quickly!, this happend to me when I use npm start, later I used yarn add .... and suddenly sound like that was fixing the issue, but was weird if I use npm instead of yarn.
Later on I realize that i need to use this app on the example folder, and not in the root, I was expecting a nodejs server not a tsdx watcher...Anyway I could get the example works for testing locally, 

Thanks! I close the issue

**Comment by andrico1234** [comment]
Thanks so much, I'll update the README to be more clear about how to run and build the package.
