### ISSUE TITLE
Skilltree

### ISSUE THREAD

**Issue by handihow** [andrico1234/beautiful-skill-tree#61]
Hi Andrico,

I am a part-time physics teacher in a secondary school (kid ages 13 - 16) and part-time freelance developer of web applications. I really like this library, so much that I was working on an application using this lib. Now I am using this  application in my school as experiment. It is working very well so I am thinking about ways to earn coin.

[https://skilltree-b6bba.firebaseapp.com/](url)

I wanted to share the link to this application with you because your library was the main inspiration and made it possible to make it. Also I found some smaller and bigger issues with the library:

**Node title class**
Can you provide a way to add a class to the node title? Right now I have managed to style it by diving into the source code, but the CSS library Bulma has default override for h1 styling.

**Theming options**
_Node desktop width_: if you set this larger (or smaller) it will cause the lines to split or overlap.
<img width="552" alt="Schermafbeelding 2020-02-16 om 11 29 15" src="https://user-images.githubusercontent.com/46277832/74603068-bbe3f880-50af-11ea-92ae-6319b31a83f1.png">

_Heading font_: The number of skills in the heading of the skill tree, seem to be set by the font selected as Node Font and not Heading Font. As you can see in the screenshot below, I have set the heading font to Roboto and the node font to Raleway. The skill count is displayed in Raleway font.
<img width="384" alt="Schermafbeelding 2020-02-16 om 11 33 21" src="https://user-images.githubusercontent.com/46277832/74603101-2ac15180-50b0-11ea-95d4-bd7dd2af05b7.png">

_Heading font color and size_: Changing these values does not have any effect. I am able to set the heading font color by changing the node font color. 

**Saving the completed state**

It would be nice if in the handleSave(
        storage: ContextStorage,
        treeId: string,
        skills: SavedDataType,
    ) method you also provide access to the number of completed skills and the total number of skills (for all skilltrees in the group) as you are giving them already in the Skilltree Group.
These data are very helpful when trying to update progress bars for the students. Right now I have implemented this with getting textContent from the skilltree group.

**Comment by andrico1234** [comment]
Hey! 

I'm loving this use case for BST!

I'll look into the issues you're having and see if I can/should update the package for them. 

FYI, we expose the completed skills data from the `SkillTreeGroup` components. Is that what you need? You can find the API details here: https://github.com/andrico1234/beautiful-skill-tree#skillgroupdatatype

You'll need to write something like this:


```
<SkillProvider>
  <SkillTreeGroup>
    {({ skillCount,  selectedSkillCount }: SkillGroupDataType) => (
      <React.Fragment>
      <ProgressChart skillCount={} selectedSkillCount={}>
      <SkillTree
        treeId="first-tree"
        title="Skill Tree"
        data={data}
        collapsible
        description="My first skill tree"
      />
      </React.Fragment>
    )}
  </SkillTreeGroup>
</SkillProvider>;
```

Let me get this right: 

- [ ] Add a classname to the node-title (I use styled components which hashes classnames, but I'll see what I can do)
- [ ] Fix the broken edges on larger screen sizes.
- [ ] Tree subtitle font should be same as heading font
- [ ] Heading font and colour values are incorrect

**Comment by handihow** [comment]
Hi Andrico

Thanks for the reply!

Indeed the total skill count and completed skill count are available in the
skill tree group. However, when it is time to save the skill tree progress,
so when you set a skill to completer, that is also the time for me to save
the overall progress so that I can display progress bars for all my
students on an overview page. So it would be nice if those numbers are
available in the save method. Right now I cannot directly get them in the
save method.

You have summarised the other issues correctly. The styling of header in
the node was easily achieved by finding the css class surrounding it.. I
believe tippy-top or something like that. But as I said, this was a bit
hard to figure out and from the start my headings were always unstyled.

Cheers
Roeland


Op di 18 feb. 2020 10:01 schreef Andrico <notifications@github.com>:

**Comment by andrico1234** [comment]
I'm going to split this ticket up into several small tickets

**Comment by andrico1234** [comment]
I'm going to close this ticket. 

And instead reference this ticket in the other issues. 

Here are links to the 4 issues I've created from this one. 

https://github.com/andrico1234/beautiful-skill-tree/issues/62
https://github.com/andrico1234/beautiful-skill-tree/issues/63
https://github.com/andrico1234/beautiful-skill-tree/issues/64
https://github.com/andrico1234/beautiful-skill-tree/issues/65

As for creating custom classes. I want to mull over that a little bit.
