### ISSUE TITLE
Horizontal tech tree

### ISSUE THREAD

**Issue by dm94** [andrico1234/beautiful-skill-tree#88]
I want to use this project with a big technology tree and I thought that the best way would be to put it horizontally as it is in the game but I don't know if it is possible.

I would like more documentation on large trees so that even if you do it vertically you don't cut the branches as you do in this picture.

![image](https://user-images.githubusercontent.com/7419213/118402817-e84c4300-b66b-11eb-9022-37dcf6f7e004.png)

I'm implementing it here, for now I'm just testing it. https://www.stiletto.live/tech

**Comment by andrico1234** [comment]
Hi @dm94 , thanks for filing an issue!

Large trees like this should be compatible, so it's likely a bug and file it as so. If you'd like you can open a pull request if you happen to find the source of the issue

**Comment by dm94** [comment]
And is it possible to place the tree in a horizontal position?

**Comment by dm94** [comment]
After some time of implementation I have fixed several bugs.
Before the lines didn't load because they were generated by SkillTreeGroup , so I had to separate each tab in different SkillProvider.

https://www.stiletto.live/tech
